export const products = [
    {
        id: 1,
        title: "Pizza 1",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/meat-chicken-mushrooms-pizza_z8ec95.png",
    },
    {
        id: 2,
        title: "Pizza 2",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/delicious-italian-pizza-with-tomato-olives-pepperoni-mushrooms_gyg5pd.png",
    },
    {
        id: 3,
        title: "Pizza 3",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/thinly-sliced-pepperoni_l1xiy7.png",
    },
    {
        id: 4,
        title: "Pizza 4",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/meat-chicken-mushrooms-pizza_z8ec95.png",
    },
    {
        id: 5,
        title: "Pizza 5",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/delicious-italian-pizza-with-tomato-olives-pepperoni-mushrooms_gyg5pd.png",
    },
    {
        id: 6,
        title: "Pizza 6",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/thinly-sliced-pepperoni_l1xiy7.png",
    },
    {
        id: 7,
        title: "Pizza 7",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/meat-chicken-mushrooms-pizza_z8ec95.png",
    },
    {
        id: 8,
        title: "Pizza 8",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/delicious-italian-pizza-with-tomato-olives-pepperoni-mushrooms_gyg5pd.png",
    },
    {
        id: 9,
        title: "Pizza 9",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/thinly-sliced-pepperoni_l1xiy7.png",
    },
    {
        id: 10,
        title: "Focaccia 1",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574565/focaccia7_jajad1.png",
    },
    {
        id: 11,
        title: "Foccaccia 2",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574564/focaccia8_tc7acl.png",
    },
    {
        id: 12,
        title: "Focaccia 3",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574564/focaccia9_pjpl6v.png",
    },
    {
        id: 13,
        title: "Focaccia 4",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574564/focaccia4_owa5v0.png",
    },
    {
        id: 14,
        title: "Focaccia 5",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574564/focaccia2_shrwgd.png",
    },
    {
        id: 15,
        title: "Focaccia 6",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574563/focaccia6_btn4fv.png",
    },
    {
        id: 16,
        title: "Focaccia 7",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574560/focaccia5_qomofl.png",
    },
    {
        id: 17,
        title: "Focaccia 8",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678574558/focaccia3_e19d6y.png",
    },
];
