export const products = [
    {
        id: 1,
        title: "Pizza 1",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/meat-chicken-mushrooms-pizza_z8ec95.png",
    },
    {
        id: 2,
        title: "Pizza 2",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/delicious-italian-pizza-with-tomato-olives-pepperoni-mushrooms_gyg5pd.png",
    },
    {
        id: 3,
        title: "Pizza 3",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/thinly-sliced-pepperoni_l1xiy7.png",
    },
    {
        id: 4,
        title: "Pizza 4",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/meat-chicken-mushrooms-pizza_z8ec95.png",
    },
    {
        id: 5,
        title: "Pizza 5",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/delicious-italian-pizza-with-tomato-olives-pepperoni-mushrooms_gyg5pd.png",
    },
    {
        id: 6,
        title: "Pizza 6",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/thinly-sliced-pepperoni_l1xiy7.png",
    },
    {
        id: 7,
        title: "Pizza 7",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/meat-chicken-mushrooms-pizza_z8ec95.png",
    },
    {
        id: 8,
        title: "Pizza 8",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/delicious-italian-pizza-with-tomato-olives-pepperoni-mushrooms_gyg5pd.png",
    },
    {
        id: 9,
        title: "Pizza 9",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "pizza",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678325678/thinly-sliced-pepperoni_l1xiy7.png",
    },
    {
        id: 10,
        title: "Focaccia 1",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678563007/focaccia-simple_ovt4vy.jpg",
    },
    {
        id: 11,
        title: "Foccaccia 2",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562983/focaccia-garden-grape_ft4oyl.webp",
    },
    {
        id: 12,
        title: "Focaccia 3",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562979/focaccia-de-murcie%CC%81lago-1_vpwzln.jpg",
    },
    {
        id: 13,
        title: "Focaccia 4",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562977/focaccia-bread-art-featured4_snuhqs.jpg",
    },
    {
        id: 14,
        title: "Focaccia 5",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562973/focaccia-garden_yggo5z.webp",
    },
    {
        id: 15,
        title: "Focaccia 6",
        price: 1900,
        stock: 5,
        description: "La clasica pizza para cualquier momento",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562971/focaccia-bread-art-featured2_smkkka.jpg",
    },
    {
        id: 16,
        title: "Focaccia 7",
        price: 1500,
        stock: 2,
        description: "Estas es la mejor pizza",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562970/focaccia-bread-art-featured3_c8za2b.jpg",
    },
    {
        id: 17,
        title: "Focaccia 8",
        price: 1450,
        stock: 5,
        description: "Ultra liviana",
        category: "focaccia",
        img: "https://res.cloudinary.com/drnrfsagl/image/upload/v1678562970/focaccia-bread-art-featured_nvp5rl.jpg",
    },
];
